export const actionTypes = {
  TOGGLE_CART_POPUP: "TOGGLE_CART_POPUP",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_CART: "REMOVE_ITEM_CART",
  INCREASE_QTY_ITEM: "INCREASE_QTY_ITEM",
  DECREASE_QTY_ITEM: "DECREASE_QTY_ITEM",
  CLEAR_CART: "CLEAR_CART",
};
